#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
VERL_ROOT="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"
QWEN3_TTS_REPO="${QWEN3_TTS_REPO:-/opt/data/private/jsj/Qwen3-TTS-main}"

cd "${VERL_ROOT}"
mkdir -p logs "${QWEN3_TTS_REPO}/checkpoints"

TS="${TS:-$(date +%Y%m%d_%H%M%S)}"
ALGORITHM="${ALGORITHM:-grpo}"
LOG="${LOG:-logs/${ALGORITHM}_all_g8_eager_${TS}.log}"

export QWEN3_TTS_REPO
export ALGORITHM
export MODEL_PATH="${MODEL_PATH:-/opt/data/private/jsj/Qwen3-TTS-12Hz-1.7B-Base}"
export TRAIN_JSONL="${TRAIN_JSONL:-${QWEN3_TTS_REPO}/data/minds14_qwen3tts_all/all_grpo.jsonl}"
export OUTPUT_DIR="${OUTPUT_DIR:-${QWEN3_TTS_REPO}/checkpoints/qwen3_tts_${ALGORITHM}_all_g8_eager_${TS}}"
export DEVICE="${DEVICE:-cuda:0}"
export ROLLOUT_DEVICES="${ROLLOUT_DEVICES:-auto}"
export GROUP_SIZE="${GROUP_SIZE:-8}"
export PROMPT_BATCH_SIZE="${PROMPT_BATCH_SIZE:-4}"
export MAX_STEPS="${MAX_STEPS:-10}"
export SAVE_FREQ="${SAVE_FREQ:-20}"
export ATTN_IMPLEMENTATION="${ATTN_IMPLEMENTATION:-eager}"
export REWARD_FN="${REWARD_FN:-recipe.qwen3_tts.combined_reward:compute_score}"
export REWARD_ASR_BACKEND="${REWARD_ASR_BACKEND:-transformers}"
export ASR_MODEL_PATH="${ASR_MODEL_PATH:-/opt/data/private/jsj/models/openai-whisper-small}"
export ASR_DEVICE_INDEX="${ASR_DEVICE_INDEX:-4}"
export ASR_BATCH_SIZE="${ASR_BATCH_SIZE:-8}"
export REWARD_WER_WEIGHT="${REWARD_WER_WEIGHT:-0.3}"
export REWARD_SIM_WEIGHT="${REWARD_SIM_WEIGHT:-0.2}"
export REWARD_JUDGE_WEIGHT="${REWARD_JUDGE_WEIGHT:-0.5}"
export REWARD_DURATION_WEIGHT="${REWARD_DURATION_WEIGHT:-0.0}"
export SPEECHJUDGE_SERVER_URL="${SPEECHJUDGE_SERVER_URL:-http://127.0.0.1:8765}"
export SPEECHJUDGE_REPO="${SPEECHJUDGE_REPO:-${QWEN3_TTS_REPO}/third_party/SpeechJudge}"
export SPEECHJUDGE_MODEL_PATH="${SPEECHJUDGE_MODEL_PATH:-${QWEN3_TTS_REPO}/pretrained/SpeechJudge-GRM}"

echo "LOG=${LOG}"
echo "OUTPUT_DIR=${OUTPUT_DIR}"
echo "ALGORITHM=${ALGORITHM}"
echo "REWARD_FN=${REWARD_FN}"
echo "USE_RAY=${USE_RAY:-1}"
echo "RAY_NUM_WORKERS=${RAY_NUM_WORKERS:-auto_from_ROLLOUT_DEVICES}"
echo "ROLLOUT_DEVICES=${ROLLOUT_DEVICES}"
echo "CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-auto_from_ROLLOUT_DEVICES}"
echo "REWARD_ASR_BACKEND=${REWARD_ASR_BACKEND}"
echo "ASR_MODEL_PATH=${ASR_MODEL_PATH}"
echo "ASR_DEVICE_INDEX=${ASR_DEVICE_INDEX}"
echo "ASR_BATCH_SIZE=${ASR_BATCH_SIZE}"
echo "REWARD_WER_WEIGHT=${REWARD_WER_WEIGHT}"
echo "REWARD_SIM_WEIGHT=${REWARD_SIM_WEIGHT}"
echo "REWARD_JUDGE_WEIGHT=${REWARD_JUDGE_WEIGHT}"
echo "REWARD_DURATION_WEIGHT=${REWARD_DURATION_WEIGHT}"
echo "SPEECHJUDGE_SERVER_URL=${SPEECHJUDGE_SERVER_URL}"
echo "SPEECHJUDGE_REPO=${SPEECHJUDGE_REPO}"
echo "SPEECHJUDGE_MODEL_PATH=${SPEECHJUDGE_MODEL_PATH}"

bash recipe/qwen3_tts/run_qwen3_tts_grpo.sh "$@" 2>&1 | tee "${LOG}"
